kind: Service
apiVersion: v1
metadata:
  name: work-orca-redis
spec:
  ports:
  - port: 6381
    targetPort: 6381
---
apiVersion: v1
kind: Endpoints
metadata:
  name: work-orca-redis
subsets:
- addresses:
  - ip: 173.37.28.229
  ports:
  - port: 6381
---
kind: Service
apiVersion: v1
metadata:
  name: work-clouddriver-redis
spec:
  ports:
  - port: 6382
    targetPort: 6382
---
apiVersion: v1
kind: Endpoints
metadata:
  name: work-clouddriver-redis
subsets:
- addresses:
  - ip: 173.37.28.229
  ports:
  - port: 6382
---
kind: Service
apiVersion: v1
metadata:
  name: work-clouddriver-ro-redis
spec:
  ports:
  - port: 16382
    targetPort: 16382
---
apiVersion: v1
kind: Endpoints
metadata:
  name: work-clouddriver-ro-redis
subsets:
- addresses:
  - ip: 173.37.28.223
  ports:
  - port: 16382
---
kind: Service
apiVersion: v1
metadata:
  name: work-others-redis
spec:
  ports:
  - port: 6380
    targetPort: 6380
---
apiVersion: v1
kind: Endpoints
metadata:
  name: work-others-redis
subsets:
- addresses:
  - ip: 173.37.28.229
  ports:
  - port: 6380
